if (EXISTS "${PROJECT_SOURCE_DIR}/../zlib/")
  message (STATUS "Sibling Zlib found.")
  set (ZLIB_FOUND TRUE)
  set (ZLIB_INCLUDE_DIRS
    "${PROJECT_SOURCE_DIR}/../zlib/"
    "${PROJECT_BINARY_DIR}/../zlib/")
  set (ZLIB_LIBRARY zlib)
  if (ZLIB_USE_STATIC_LIBS)
    message (STATUS "Using static sibling Zlib.")
    set (ZLIB_LIBRARY zlibstatic)
  else ()
    message (STATUS "Using shared sibling Zlib.")
  endif ()
  set (ZLIB_LIBRARIES ${ZLIB_LIBRARY})
elseif (EXISTS "${PROJECT_SOURCE_DIR}/../../zlib/")
  message (STATUS "Sibling Zlib found.")
  set (ZLIB_FOUND TRUE)
  set (ZLIB_INCLUDE_DIRS
    "${PROJECT_SOURCE_DIR}/../../zlib/"
    "${PROJECT_BINARY_DIR}/../../zlib/")
  set (ZLIB_LIBRARY zlib)
  if (ZLIB_USE_STATIC_LIBS)
    message (STATUS "Using static sibling Zlib.")
    set (ZLIB_LIBRARY zlibstatic)
  else ()
    message (STATUS "Using shared sibling Zlib.")
  endif ()
  set (ZLIB_LIBRARIES ${ZLIB_LIBRARY})
else ()
  message (STATUS "Sibling Zlib NOT found.")
endif ()
